import {initializeApp} from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-app.js';
import {getAuth,signInAnonymously,setPersistence,browserLocalPersistence} from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-auth.js';
import {getFirestore,collection,doc,addDoc,setDoc,getDoc,getDocs,onSnapshot,runTransaction,query,orderBy,serverTimestamp} from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-firestore.js';
import {firebaseConfig} from './firebase-config.js';
const $=id=>document.getElementById(id), money=n=>'Rp'+fmt(Math.round(Number(n)||0)),fmt=n=>Math.round(Number(n)||0).toLocaleString('id-ID'), num=v=>{let s=String(v??'').trim();if(!s)return 0;if(!/^\d{1,3}(\.\d{3})*$|^\d+$/.test(s))throw Error('Angka harus bulat. Gunakan titik hanya untuk ribuan, contoh 15.000.');return Number(s.replaceAll('.',''))}, val=id=>$(id)?.value??'', nval=id=>num(val(id)), h=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])), today=()=>new Date().toLocaleDateString('en-CA'), uid=()=>auth.currentUser?.uid, now=()=>new Date().toISOString();
let firebase,auth,db,unsubs=[],view='dashboard',section='home',state={products:[],contacts:[],entries:[],reportChannel:'all',tray:{available:0,broken:0,unitCost:0}}, selectedMonth=new Date().toISOString().slice(0,7), reportChannel='all';
const show=(msg,error=false)=>{let el=$('notice');el.textContent=msg;el.className='notice show'+(error?' error':'');clearTimeout(show.timer);show.timer=setTimeout(()=>el.className='notice',5000)};
const path=(col,id)=>doc(db,'users',uid(),col,id), list=col=>collection(db,'users',uid(),col), entryRef=()=>doc(list('entries'));
const product=id=>state.products.find(x=>x.id===id),contact=id=>state.contacts.find(x=>x.id===id);
const stock=p=>(p?.lots||[]).reduce((a,l)=>a+l.qty,0), costFIFO=(p,qty)=>{let left=qty,total=0,lots=(p?.lots||[]).map(x=>({...x}));for(const l of lots){let take=Math.min(left,l.qty);if(take>0){total+=take*l.cost/l.base;l.qty-=take;left-=take}}if(left>0)throw Error('Stok telur tidak cukup. Tersedia '+fmt(qty-left)+' gram dari '+fmt(qty)+' gram.');return {cost:Math.round(total),lots:lots.filter(l=>l.qty>0)}};
const card=(label,value,detail='',cls='')=>`<div class="card"><span class="metric-label">${label}</span><div class="metric-value ${cls}">${value}</div><p class="small">${detail}</p></div>`;
const field=(label,id,value='',attrs='',wide=false)=>`<div class="field ${wide?'wide':''}"><label for="${id}">${label}</label><input id="${id}" value="${h(value)}" ${attrs}></div>`;
const choose=(label,id,options,wide=false)=>`<div class="field ${wide?'wide':''}"><label for="${id}">${label}</label><select id="${id}">${options.map(([v,l])=>`<option value="${h(v)}">${h(l)}</option>`).join('')}</select></div>`;
const prodOptions=()=>state.products.filter(x=>x.active!==false).map(x=>[x.id,x.name]),contactOptions=(type,anonymous=false)=>[...(anonymous?[['','Pembeli umum (tunai)']]:[]),...state.contacts.filter(x=>x.kind===type).map(x=>[x.id,x.name])], channels=[['offline','Offline'],['shopee','Shopee'],['online','Online lainnya']], trayOptions=[['none','Tanpa tray'],['swap','Tukar tray'],['loan','Pinjam tray'],['buy','Beli tray'],['mixed','Tukar + beli tray']];
function modal(title,html){$('modalTitle').textContent=title;$('modalBody').innerHTML=html;$('modal').hidden=false}function closeModal(){$('modal').hidden=true;$('modalBody').innerHTML=''};
$('modalClose').onclick=closeModal;$('modal').addEventListener('click',e=>{if(e.target===$('modal'))closeModal()});$('nav').onclick=e=>{let btn=e.target.closest('[data-page]');if(btn){navigate(btn.dataset.page)}};
function navigate(page){if(!['dashboard','sale','stock','reports','more'].includes(page))return;view=page;section='home';render();window.scrollTo({top:0,behavior:'instant'});}
window.addEventListener('error',e=>{console.error('Cangkang Mas:',e.error||e.message);show('Ada kesalahan aplikasi. Buka Console untuk detail.',true)});
async function save(label,fn){try{let b=$('saveBtn');if(b){b.disabled=true;b.textContent='Menyimpan…'}await fn();closeModal();show(label+' berhasil disimpan.')}catch(e){show(e.message||'Gagal menyimpan.',true);let b=$('saveBtn');if(b){b.disabled=false;b.textContent='Simpan'}}}
function watchers(){unsubs.forEach(x=>x());unsubs=[];for(const col of ['products','contacts','entries']){unsubs.push(onSnapshot(list(col),s=>{state[col]=s.docs.map(d=>({id:d.id,...d.data()}));if(col==='entries')state.entries.sort((a,b)=>(b.createdAt||'').localeCompare(a.createdAt||''));render()},e=>show('Gagal membaca '+col+': '+e.message,true)))}unsubs.push(onSnapshot(path('meta','tray'),s=>{state.tray=s.exists()?s.data():{available:0,broken:0,unitCost:0};render()},e=>show(e.message,true)))}
function render(){if(!uid())return;document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===view));const pages={dashboard:dashboard,sale:salePage,stock:stockPage,reports:reportsPage,more:morePage};$('content').innerHTML=(pages[view]||dashboard)();wirePage()}
function dashboard(){let month=state.entries.filter(e=>e.date?.startsWith(selectedMonth)),profit=month.reduce((a,e)=>a+(e.profit||0),0),offline=month.filter(e=>e.channel==='offline').reduce((a,e)=>a+(e.profit||0),0),online=month.filter(e=>['shopee','online'].includes(e.channel)).reduce((a,e)=>a+(e.profit||0),0),receivable=state.contacts.filter(c=>c.kind==='customer').reduce((a,c)=>a+(c.debt||0),0),owed=state.contacts.filter(c=>c.kind==='customer').reduce((a,c)=>a+(c.trayDue||0),0),dueEgg=state.contacts.filter(c=>c.kind==='customer').reduce((a,c)=>a+(c.eggDue||0),0);return `<div class="hero"><div><div class="small">CANGKANG MAS · ${h(selectedMonth)}</div><h2>${money(profit)}</h2><p>Laba tercatat bulan terpilih · Offline + Online</p></div><img class="hero-logo" src="assets/logo.png" alt="Logo Cangkang Mas"></div><div class="grid four">${card('Stok telur',fmt(state.products.reduce((a,p)=>a+stock(p),0))+' gram','Semua jenis')}${card('Tray fisik layak',fmt(state.tray.available||0)+' pcs','Tidak termasuk tray di customer')}${card('Laba offline',money(offline),'Bulan ini','green')}${card('Laba online',money(online),'Shopee + online lain','green')}</div><div class="card"><h2>Transaksi cepat</h2><div class="actions"><button class="action" data-action="purchase"><span>▣</span>Kulak telur</button><button class="action" data-action="sale"><span>🛒</span>Jual telur</button><button class="action" data-action="tray"><span>⇄</span>Tray</button><button class="action" data-action="return"><span>↩</span>Retur telur</button></div></div><div class="card"><h2>Perlu ditindaklanjuti</h2><div class="grid">${card('Bon customer',money(receivable),'Belum dibayar','orange')}${card('Tray di customer',fmt(owed)+' pcs','Belum kembali','orange')}${card('Telur pengganti',fmt(dueEgg)+' gram','Belum dikirim','orange')}${card('Tray rusak',fmt(state.tray.broken||0)+' pcs','Tidak layak digunakan')}</div></div>${recent(6)}`}
function recent(limit=30){let arr=state.entries.slice(0,limit);return `<div class="card"><div class="row"><h2>Riwayat terbaru</h2><button class="outline" data-action="history">Lihat semua</button></div>${arr.length?arr.map(e=>`<div class="list-row"><div><b>${h(e.label||e.type)}</b><small>${h(e.date)} · ${h(e.partyName||e.channel||'')} ${e.weight? '· '+fmt(e.weight)+' gram':''}</small></div><aside><b class="${(e.profit||0)<0?'red':'green'}">${e.type==='sale'?money(e.revenue):e.type==='expense'?'-'+money(e.amount):e.type==='purchase'?money(e.amount):e.profit?money(e.profit):'—'}</b><small>${e.profit!==undefined?'Laba '+money(e.profit):h(e.status||'')}</small><button class="outline" data-receipt="${h(e.id)}" style="margin-top:5px">Detail</button></aside></div>`).join(''):'<div class="empty">Belum ada transaksi.</div>'}</div>`}
function salePage(){return `<h1 class="page-title">Jual telur</h1><p class="subtitle">Satu jenis telur per transaksi. Stok, FIFO dan laba dihitung otomatis.</p><div class="card"><div class="row wrap"><h2>Input penjualan</h2><button class="outline" data-action="contact-customer">+ Customer</button></div>${saleForm()}</div>${recent(8)}`}
function saleForm(){return `<form id="saleForm"><div class="form-grid">${choose('Saluran penjualan','sChannel',channels)}${choose('Customer','sCustomer',contactOptions('customer',true))}${choose('Jenis telur','sProduct',prodOptions())}${field('Berat (gram)','sWeight','','inputmode="numeric" placeholder="Contoh: 1.500" required')}${field('Harga jual per kg (Rp) · Offline/online lain','sPrice','','inputmode="numeric" placeholder="25.000"')}${field('Uang bersih Shopee (Rp) · Jika Shopee','sNet','','inputmode="numeric" placeholder="26.970"')}${choose('Perlakuan tray','sTrayMode',trayOptions)}<div class="field" id="sTrayFields" hidden><label>Tray keluar (pcs)</label><input id="sTrayOut" inputmode="numeric" placeholder="0"><label id="sTrayInLabel">Tray diterima (pcs)</label><input id="sTrayIn" inputmode="numeric" placeholder="0"><label id="sTrayBuyLabel">Tray dibeli (pcs)</label><input id="sTrayBuy" inputmode="numeric" placeholder="0"><label id="sTrayPriceLabel">Harga tray per pcs (Rp)</label><input id="sTrayPrice" inputmode="numeric" placeholder="0"></div>${field('Ongkir ditagih customer (Rp) · Opsional','sDelivery','','inputmode="numeric" placeholder="0"')}${field('Biaya tambahan usaha (Rp) · Opsional','sCost','','inputmode="numeric" placeholder="0"')}${choose('Pembayaran','sPay',[['cash','Tunai'],['transfer','Transfer'],['qris','QRIS'],['credit','Bon / cicilan']])}${field('Dibayar sekarang (Rp) · Jika bon','sPaid','','inputmode="numeric" placeholder="0"')}${field('Catatan (opsional)','sNote','','placeholder="Harga khusus, nomor pesanan, dll"',true)}</div><div class="summary" id="saleSummary">Pilih jenis telur dan isi berat untuk melihat estimasi.</div><div class="form-actions"><button type="submit" class="primary" id="saveBtn">Simpan penjualan</button></div></form>`}
function stockPage(){return `<h1 class="page-title">Persediaan</h1><p class="subtitle">Stok aktual berdasarkan pembelian dan penjualan; FIFO per jenis telur.</p><div class="row wrap" style="margin-bottom:14px"><button class="primary" data-action="product">+ Jenis telur</button><button class="secondary" data-action="purchase">+ Kulak telur</button><button class="secondary" data-action="adjust">Koreksi stok</button></div><div class="grid">${state.products.map(p=>`<div class="card"><div class="row"><h2>${h(p.name)}</h2><span class="pill ${p.active===false?'warn':''}">${p.active===false?'Nonaktif':'Aktif'}</span></div><div class="metric-value">${fmt(stock(p))} gram</div><p>Harga jual ${money(p.price||0)}/kg</p><p>Modal FIFO berikutnya ${p.lots?.length?money(Math.round(p.lots[0].cost*1000/p.lots[0].base))+'/kg':'—'}</p><div class="row"><button class="outline" data-edit-product="${h(p.id)}">Edit</button><button class="outline" data-adjust-product="${h(p.id)}">Koreksi</button></div></div>`).join('')||'<div class="card">Belum ada jenis telur. Tambahkan dahulu.</div>'}</div><div class="card"><h2>Tray</h2><div class="grid">${card('Tray layak',fmt(state.tray.available||0)+' pcs')}${card('Tray rusak',fmt(state.tray.broken||0)+' pcs')}${card('Modal tray rata-rata',money(state.tray.unitCost||0)+'/pcs')}</div><div class="row wrap"><button class="primary" data-action="tray">Transaksi tray</button><button class="secondary" data-action="tray-adjust">Koreksi tray</button></div></div>`}
function morePage(){let debts=state.contacts.filter(c=>c.kind==='customer');return `<h1 class="page-title">Lainnya</h1><p class="subtitle">Pengaturan data dan transaksi pendukung.</p><div class="card"><h2>Kelola usaha</h2><div class="actions"><button class="action" data-action="purchase"><span>▣</span>Kulak telur</button><button class="action" data-action="tray"><span>⇄</span>Kulak / tukar tray</button><button class="action" data-action="return"><span>↩</span>Retur telur</button><button class="action" data-action="expense"><span>▤</span>Biaya usaha</button><button class="action" data-action="product"><span>◉</span>Jenis telur</button><button class="action" data-action="contact-customer"><span>♙</span>Customer</button><button class="action" data-action="contact-supplier"><span>♧</span>Supplier</button><button class="action" data-action="backup"><span>⇩</span>Ekspor data</button></div></div><div class="card"><div class="row wrap"><h2>Customer & bon</h2><button class="outline" data-action="contact-customer">+ Customer</button></div>${debts.length?debts.map(c=>`<div class="list-row"><div><b>${h(c.name)}</b><small>Bon ${money(c.debt||0)} · Tray ${fmt(c.trayDue||0)} pcs · Telur pengganti ${fmt(c.eggDue||0)} gram</small></div><aside><button class="outline" data-contact="${h(c.id)}">Detail / bayar</button></aside></div>`).join(''):'<p class="muted">Belum ada customer.</p>'}</div><div class="card"><div class="row"><h2>Supplier / kandang</h2><button class="outline" data-action="contact-supplier">+ Supplier</button></div>${state.contacts.filter(c=>c.kind==='supplier').map(c=>`<div class="list-row"><div><b>${h(c.name)}</b><small>Tray perlu dikembalikan: ${fmt(c.trayDue||0)} pcs · Telur pengganti dari supplier: ${fmt(c.eggDue||0)} gram</small></div><button class="outline" data-contact="${h(c.id)}">Detail</button></div>`).join('')||'<p class="muted">Belum ada supplier.</p>'}</div><div class="card"><h2>Riwayat transaksi</h2><button class="secondary" data-action="history">Buka riwayat & nota</button></div>`}
function reportsPage(){let entries=state.entries.filter(e=>e.date?.startsWith(selectedMonth)),selected=state.reportChannel,filtered=entries.filter(e=>selected==='all'||(selected==='online'?['shopee','online'].includes(e.channel):e.channel===selected)),rev=filtered.reduce((a,e)=>a+(e.revenue||0),0),cogs=filtered.reduce((a,e)=>a+(e.cogs||0),0),costs=filtered.reduce((a,e)=>a+(e.cost||0)+(e.type==='expense'?e.amount||0:0),0),profit=filtered.reduce((a,e)=>a+(e.profit||0),0);let sales=filtered.filter(e=>e.type==='sale');return `<h1 class="page-title">Laporan</h1><p class="subtitle">Laba transaksi bulan terpilih; cicilan bon bukan penjualan baru.</p><div class="card"><div class="filter"><input type="month" id="reportMonth" value="${h(selectedMonth)}"><select id="reportChannel">${[['all','Semua'],['offline','Offline'],['online','Online gabungan'],['shopee','Shopee']].map(([v,l])=>`<option value="${v}" ${v===selected?'selected':''}>${l}</option>`).join('')}</select><button class="outline" data-action="csv">Ekspor Excel (CSV)</button></div></div><div class="grid four">${card('Laba tercatat',money(profit),'Pendapatan − HPP − biaya',profit<0?'red':'green')}${card('Pendapatan',money(rev),'Penjualan bersih untuk Shopee')}${card('HPP terjual',money(cogs),'FIFO telur + modal tray')}${card('Biaya terkait',money(costs),'Termasuk biaya usaha')}</div><div class="card"><h2>Per saluran</h2><div class="table-scroll"><table class="table"><tr><th>Saluran</th><th>Penjualan</th><th>Laba</th></tr>${channels.map(([v,l])=>{let e=entries.filter(x=>x.channel===v);return `<tr><td>${l}</td><td>${money(e.reduce((a,x)=>a+(x.revenue||0),0))}</td><td>${money(e.reduce((a,x)=>a+(x.profit||0),0))}</td></tr>`}).join('')}</table></div><p class="help">Biaya bersama tanpa saluran khusus tetap masuk laba gabungan. Agar laba masing-masing saluran tepat, pilih saluran ketika mencatat biaya.</p></div><div class="card"><h2>Penjualan bulan ini (${sales.length})</h2>${sales.length?sales.map(e=>`<div class="list-row"><div><b>${h(e.partyName||'Pembeli umum')} · ${h(e.productName)}</b><small>${h(e.date)} · ${fmt(e.weight)} gram</small></div><aside><b>${money(e.revenue)}</b><small>Laba ${money(e.profit||0)}</small></aside></div>`).join(''):'<p class="muted">Belum ada penjualan dalam periode ini.</p>'}</div>`}
function wirePage(){document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>action(b.dataset.action));document.querySelectorAll('[data-contact]').forEach(b=>b.onclick=()=>contactDetail(b.dataset.contact));document.querySelectorAll('[data-edit-product]').forEach(b=>b.onclick=()=>productForm(b.dataset.editProduct));document.querySelectorAll('[data-adjust-product]').forEach(b=>b.onclick=()=>adjustForm(b.dataset.adjustProduct));document.querySelectorAll('[data-receipt]').forEach(b=>b.onclick=()=>receipt(b.dataset.receipt));if($('saleForm')){for(const id of ['sProduct','sWeight','sPrice','sNet','sChannel','sTrayMode','sTrayOut','sTrayIn','sTrayBuy','sTrayPrice','sDelivery','sCost','sPay','sPaid'])$(id).addEventListener('input',saleEstimate);$('sProduct').addEventListener('change',()=>{$('sPrice').value=fmt(product(val('sProduct'))?.price||0);saleEstimate()});$('sChannel').addEventListener('change',()=>{let sh=val('sChannel')==='shopee';$('sNet').closest('.field').hidden=!sh;$('sPrice').closest('.field').hidden=sh;$('sDelivery').closest('.field').hidden=sh;$('sPay').closest('.field').hidden=sh;if(sh)$('sPay').value='cash';saleEstimate()});$('sPay').addEventListener('change',()=>{$('sPaid').closest('.field').hidden=val('sPay')!=='credit'});$('sPrice').value=fmt(product(val('sProduct'))?.price||0);$('sPay').dispatchEvent(new Event('change'));$('sChannel').dispatchEvent(new Event('change'));$('saleForm').onsubmit=e=>{e.preventDefault();save('Penjualan',recordSale)}}if($('reportMonth'))$('reportMonth').onchange=e=>{selectedMonth=e.target.value;render()};if($('reportChannel'))$('reportChannel').onchange=e=>{state.reportChannel=e.target.value;render()}}
function saleEstimate(){let mode=val('sTrayMode'),el=$('sTrayFields');if(el)el.hidden=mode==='none';if($('sTrayInLabel'))$('sTrayInLabel').hidden=$('sTrayIn').hidden=!['swap','mixed'].includes(mode);if($('sTrayBuyLabel'))$('sTrayBuyLabel').hidden=$('sTrayBuy').hidden=!['buy','mixed'].includes(mode);if($('sTrayPriceLabel'))$('sTrayPriceLabel').hidden=$('sTrayPrice').hidden=!['buy','mixed'].includes(mode);if(!el)return;try{let p=product(val('sProduct')),w=nval('sWeight'),x=w?costFIFO(p,w):{cost:0},trayBuy=['buy','mixed'].includes(mode)?nval('sTrayBuy'):0,trayPrice=nval('sTrayPrice'),income=val('sChannel')==='shopee'?nval('sNet'):Math.round(w*nval('sPrice')/1000)+nval('sDelivery')+trayBuy*trayPrice,fee=nval('sCost'),trayCost=trayBuy*(state.tray.unitCost||0),profit=income-x.cost-fee-trayCost;let warning=w>stock(p)?'<div class="warnbox">Berat melebihi stok tersedia.</div>':'';$('saleSummary').innerHTML=`<span class="metric-label">Stok: ${fmt(stock(p))} gram · Perkiraan HPP FIFO ${money(x.cost)}</span><strong>${money(income)}</strong><div class="row"><span>Estimasi laba transaksi</span><b class="${profit<0?'red':'green'}">${money(profit)}</b></div>${warning}<p class="hint">Saldo tray dan bon akan disesuaikan saat disimpan.</p>`}catch(e){$('saleSummary').textContent=e.message}}
function action(a){if(a==='sale'){navigate('sale')}else if(a==='purchase')purchaseForm();else if(a==='product')productForm();else if(a==='tray')trayForm();else if(a==='return')returnForm();else if(a==='expense')expenseForm();else if(a==='adjust')adjustForm();else if(a==='tray-adjust')trayAdjust();else if(a==='contact-customer')contactForm('customer');else if(a==='contact-supplier')contactForm('supplier');else if(a==='history')historyForm();else if(a==='csv')exportCSV();else if(a==='backup')exportJSON()}
function contactForm(kind,id){let c=contact(id)||{};modal((id?'Edit ':'Tambah ')+(kind==='customer'?'customer':'supplier'),`<form id="contactForm"><div class="form-grid">${field('Nama','cName',c.name||'','required',true)}${field('WhatsApp (opsional)','cPhone',c.phone||'','inputmode="tel"')}${field('Alamat (opsional)','cAddress',c.address||'','')}${field('Harga khusus per kg (opsional)','cSpecial',c.special||'','inputmode="numeric" placeholder="0"')}</div><div class="form-actions"><button class="primary" id="saveBtn">Simpan</button></div></form>`);$('contactForm').onsubmit=e=>{e.preventDefault();save('Data pihak',async()=>{let data={name:val('cName').trim(),phone:val('cPhone').trim(),address:val('cAddress').trim(),special:nval('cSpecial'),kind};if(!data.name)throw Error('Nama wajib diisi.');await setDoc(id?path('contacts',id):doc(list('contacts')),data,{merge:true})})}}
function productForm(id){let p=product(id)||{};modal(id?'Edit jenis telur':'Tambah jenis telur',`<form id="productForm"><div class="form-grid">${field('Nama jenis telur','pName',p.name||'','required',true)}${field('Harga jual normal / kg (Rp)','pPrice',p.price?fmt(p.price):'','required inputmode="numeric" placeholder="25.000"')}${choose('Status','pActive',[['yes','Aktif'],['no','Nonaktif']])}</div><p class="help">Stok dan modal masuk melalui Kulak Telur atau pengisian Stok Awal. Jangan mengubah stok melalui harga jual.</p><div class="form-actions"><button class="primary" id="saveBtn">Simpan</button></div></form>`);$('pActive').value=p.active===false?'no':'yes';$('productForm').onsubmit=e=>{e.preventDefault();save('Jenis telur',async()=>{let name=val('pName').trim();if(!name)throw Error('Nama jenis telur wajib diisi.');await setDoc(id?path('products',id):doc(list('products')),{name,price:nval('pPrice'),active:val('pActive')==='yes',...(!id?{lots:[]}:{}),updatedAt:now()},{merge:true})})}}
function purchaseForm(){if(!state.products.length)return show('Tambahkan jenis telur terlebih dahulu.',true);modal('Kulak telur',`<form id="purchaseForm"><div class="form-grid">${field('Tanggal','bDate',today(),'type="date" required')}${choose('Supplier / kandang','bSupplier',[['','Tanpa supplier'],...contactOptions('supplier')])}${choose('Jenis telur','bProduct',prodOptions())}${choose('Ukuran ikat','bBundle',[['10000','10 kg'],['15000','15 kg']])}${field('Jumlah ikat','bCount','1','required inputmode="numeric"')}${field('Harga kulak / kg (Rp)','bPrice','','required inputmode="numeric" placeholder="23.500"')}<label class="check wide"><input type="checkbox" id="bActualSwitch"> Berat aktual berbeda dari nominal</label><div class="field wide" id="actualField" hidden><label>Berat aktual (gram)</label><input id="bActual" inputmode="numeric" placeholder="Contoh: 9.850"></div>${field('Jumlah tray diterima (pcs)','bTrayOut','0','inputmode="numeric"')}${field('Jumlah tray ditukar / diserahkan (pcs)','bTrayIn','0','inputmode="numeric"')}${field('Jumlah tray dibeli (pcs)','bTrayBought','0','inputmode="numeric"')}${field('Harga beli tray per pcs (Rp)','bTrayPrice','0','inputmode="numeric"')}${field('Biaya kulak / ongkir aktual (Rp) · Opsional','bCost','0','inputmode="numeric"')}${field('Catatan (opsional)','bNote','','',true)}</div><div id="purchaseSum" class="summary"></div><div class="form-actions"><button class="primary" id="saveBtn">Simpan kulak</button></div></form>`);$('bActualSwitch').onchange=()=>{$('actualField').hidden=!$('bActualSwitch').checked;purchaseEstimate()};['bBundle','bCount','bActual','bPrice','bTrayOut','bTrayIn','bTrayBought','bTrayPrice','bCost'].forEach(id=>$(id).addEventListener('input',purchaseEstimate));purchaseEstimate();$('purchaseForm').onsubmit=e=>{e.preventDefault();save('Kulak telur',recordPurchase)}}
function purchaseEstimate(){try{let w=$('bActualSwitch').checked?nval('bActual'):nval('bBundle')*nval('bCount'),egg=Math.round(w*nval('bPrice')/1000),tray=nval('bTrayBought')*nval('bTrayPrice'),cost=nval('bCost');$('purchaseSum').innerHTML=`<span class="metric-label">Berat masuk</span><strong>${fmt(w)} gram</strong><div class="row"><span>Telur + tray + biaya</span><b>${money(egg+tray+cost)}</b></div>`}catch(e){$('purchaseSum').textContent=e.message}}
function trayForm(){modal('Transaksi tray',`<form id="trayForm"><div class="form-grid">${field('Tanggal','tDate',today(),'type="date" required')}${choose('Jenis transaksi','tMode',[['buy','Kulak tray'],['swap','Tukar tray'],['loan','Pinjamkan tray'],['return','Pengembalian tray'],['sell','Jual tray'],['broken','Tray rusak'],['replace','Tukar tray rusak ke supplier']])}${choose('Customer / supplier','tParty',[['','Tanpa pihak'],...state.contacts.map(c=>[c.id,c.name+' ('+(c.kind==='customer'?'Customer':'Supplier')+')'])])}${field('Tray keluar (pcs)','tOut','0','inputmode="numeric"')}${field('Tray masuk (pcs)','tIn','0','inputmode="numeric"')}${field('Harga per tray (Rp) · Untuk beli/jual','tPrice','0','inputmode="numeric"')}${choose('Pembayaran · Untuk jual','tPay',[['cash','Tunai'],['transfer','Transfer'],['qris','QRIS'],['credit','Bon']])}${field('Dibayar sekarang (Rp) · Jika bon','tPaid','0','inputmode="numeric"')}${field('Catatan','tNote','','',true)}</div><p class="help">Pinjam: tray keluar. Kembali: tray masuk. Tukar: isi keduanya. Kulak: tray masuk. Jual: tray keluar. Rusak: tray keluar dari stok layak pakai.</p><div class="form-actions"><button class="primary" id="saveBtn">Simpan tray</button></div></form>`);$('trayForm').onsubmit=e=>{e.preventDefault();save('Transaksi tray',recordTray)}}
function returnForm(){modal('Retur telur busuk',`<form id="returnForm"><div class="form-grid">${field('Tanggal','rDate',today(),'type="date" required')}${choose('Asal retur','rDirection',[['customer','Dari customer'],['supplier','Ke supplier / kandang'],['internal','Telur busuk di gudang']])}${choose('Customer / supplier','rParty',[['','Pilih pihak'],...state.contacts.map(c=>[c.id,c.name+' ('+c.kind+')'])])}${choose('Jenis telur','rProduct',prodOptions())}${field('Berat telur busuk (gram)','rWeight','','required inputmode="numeric"')}${choose('Penanganan','rResolution',[['none','Tanpa penggantian'],['refund','Penggantian uang'],['replace','Penggantian telur di kemudian hari']])}${field('Nilai uang pengganti (Rp) · Jika uang','rRefund','0','inputmode="numeric"')}${field('Catatan / nomor transaksi asal','rNote','','',true)}</div><div class="warnbox">Retur customer: telur busuk tidak ditambahkan ke stok layak jual. Retur supplier/gudang: berat busuk dikeluarkan dari stok layak jual dengan FIFO. Penggantian telur dicatat sebagai kewajiban atau hak sampai diselesaikan.</div><div class="form-actions"><button class="primary" id="saveBtn">Simpan retur</button></div></form>`);$('returnForm').onsubmit=e=>{e.preventDefault();save('Retur',recordReturn)}}
function expenseForm(){modal('Biaya operasional',`<form id="expenseForm"><div class="form-grid">${field('Tanggal','xDate',today(),'type="date" required')}${choose('Alokasi biaya','xChannel',[['shared','Biaya bersama (gabungan)'],...channels])}${field('Nama biaya','xName','','required placeholder="Bensin, listrik, parkir, dll"')}${field('Nominal (Rp)','xAmount','','required inputmode="numeric"')}${field('Catatan','xNote','','',true)}</div><div class="form-actions"><button class="primary" id="saveBtn">Simpan biaya</button></div></form>`);$('expenseForm').onsubmit=e=>{e.preventDefault();save('Biaya usaha',async()=>{let amount=nval('xAmount');if(amount<=0||!val('xName').trim())throw Error('Nama biaya dan nominal harus diisi.');await addDoc(list('entries'),{type:'expense',label:'Biaya: '+val('xName').trim(),channel:val('xChannel'),date:val('xDate'),amount,profit:-amount,note:val('xNote'),createdAt:now()})})}}
function adjustForm(id){if(!state.products.length)return show('Tambahkan jenis telur terlebih dahulu.',true);modal('Koreksi stok telur',`<form id="adjustForm"><div class="form-grid">${choose('Jenis telur','aProduct',prodOptions())}${field('Stok fisik sebenarnya (gram)','aStock','','required inputmode="numeric"')}${field('Alasan koreksi','aReason','','required placeholder="Stok awal / selisih timbang / pecah"',true)}${field('Modal / kg (Rp) · Hanya untuk penambahan','aCost','0','inputmode="numeric"')}</div><p class="help">Jika stok fisik lebih sedikit, selisih dikeluarkan melalui FIFO. Jika lebih banyak, stok tambahan dibuat sebagai lot baru menggunakan modal per kg yang Anda isi.</p><div class="form-actions"><button class="primary" id="saveBtn">Simpan koreksi</button></div></form>`);if(id)$('aProduct').value=id;$('adjustForm').onsubmit=e=>{e.preventDefault();save('Koreksi stok',recordAdjust)}}
function trayAdjust(){modal('Koreksi tray fisik',`<form id="trayAdjustForm"><div class="form-grid">${field('Tray layak fisik (pcs)','atAvail',fmt(state.tray.available||0),'required inputmode="numeric"')}${field('Tray rusak fisik (pcs)','atBroken',fmt(state.tray.broken||0),'required inputmode="numeric"')}${field('Modal tray / pcs (Rp) · Untuk stok awal','atCost',fmt(state.tray.unitCost||0),'inputmode="numeric"')}${field('Alasan','atReason','','required placeholder="Stok awal / opname"',true)}</div><div class="form-actions"><button class="primary" id="saveBtn">Simpan</button></div></form>`);$('trayAdjustForm').onsubmit=e=>{e.preventDefault();save('Stok tray',async()=>{if(!val('atReason').trim())throw Error('Alasan wajib diisi.');let available=nval('atAvail'),broken=nval('atBroken'),unitCost=nval('atCost');await runTransaction(db,async tx=>{let ref=path('meta','tray'),s=await tx.get(ref),old=s.exists()?s.data():{available:0,broken:0};tx.set(ref,{...old,available,broken,unitCost});tx.set(entryRef(),{type:'adjust',label:'Koreksi tray: '+val('atReason'),date:today(),trayDelta:available-(old.available||0),createdAt:now()})})})}}
function contactDetail(id){let c=contact(id);if(!c)return;modal(c.name,`<div class="grid">${card('Bon',money(c.debt||0))}${card('Tray belum kembali',fmt(c.trayDue||0)+' pcs')}${card('Telur pengganti',fmt(c.eggDue||0)+' gram')}${card('Uang pengganti',money(c.refundDue||0))}</div><div class="row wrap" style="margin:14px 0"><button class="secondary" id="editContact">Edit data</button><button class="secondary" id="settleContact">Bayar bon / selesaikan retur</button><button class="secondary" id="trayContact">Transaksi tray</button></div><p class="muted">${h(c.phone||'')} ${h(c.address||'')}</p>`);$('editContact').onclick=()=>contactForm(c.kind,id);$('settleContact').onclick=()=>settlementForm(id);$('trayContact').onclick=()=>trayForm()}
function settlementForm(id){let c=contact(id);modal('Pembayaran / penggantian · '+c.name,`<form id="settleForm"><div class="form-grid">${choose('Penyelesaian','qMode',[['debt','Customer bayar bon'],['refund','Uang retur dibayar / diterima'],['egg','Telur pengganti dikirim / diterima']])}${field('Jumlah (Rp atau gram)','qAmount','','required inputmode="numeric"')}${choose('Jenis telur pengganti (jika telur)','qProduct',prodOptions())}${choose('Metode pembayaran','qPay',[['cash','Tunai'],['transfer','Transfer'],['qris','QRIS']])}${field('Catatan','qNote','','',true)}</div><p class="help">Jika mengganti telur untuk customer, stok FIFO akan berkurang dan biaya pengganti dicatat saat dikirim. Jika menerima telur pengganti supplier, gunakan menu Kulak Telur untuk menambah stok dengan modal Rp0 sesuai kesepakatan, kemudian selesaikan hak penggantian di sini.</p><div class="form-actions"><button class="primary" id="saveBtn">Simpan penyelesaian</button></div></form>`);$('settleForm').onsubmit=e=>{e.preventDefault();save('Penyelesaian',()=>recordSettlement(id))}}
function historyForm(){modal('Riwayat seluruh transaksi',`<div class="filter"><input type="month" id="historyMonth" value="${h(selectedMonth)}"><button class="outline" id="historyAll">Semua tanggal</button></div><div id="historyList"></div>`);const draw=()=>{$('historyList').innerHTML=state.entries.filter(e=>!val('historyMonth')||e.date?.startsWith(val('historyMonth'))).map(e=>`<div class="list-row"><div><b>${h(e.label||e.type)}</b><small>${h(e.date)} · ${h(e.partyName||e.channel||'')} ${e.weight?fmt(e.weight)+' gram':''}</small></div><aside>${e.revenue!==undefined?money(e.revenue):e.amount!==undefined?money(e.amount):'—'}<small>Laba ${money(e.profit||0)}</small><button class="outline" data-entry="${h(e.id)}">Detail / nota</button></aside></div>`).join('')||'<div class="empty">Tidak ada transaksi.</div>';$('historyList').querySelectorAll('[data-entry]').forEach(b=>b.onclick=()=>receipt(b.dataset.entry))};$('historyMonth').onchange=draw;$('historyAll').onclick=()=>{$('historyMonth').value='';draw()};draw()}
function receipt(id){let e=state.entries.find(x=>x.id===id);if(!e)return;modal('Detail transaksi',`<div class="print-receipt"><img src="assets/logo.png" alt="Cangkang Mas"><h2>CANGKANG MAS</h2><p style="text-align:center">${h(e.label||e.type)}<br>${h(e.date)} · ${h(id.slice(0,10))}</p><div class="divider"></div><p>Nama: ${h(e.partyName||'Pembeli umum')}</p>${e.productName?`<p>Telur: ${h(e.productName)}</p>`:''}${e.weight?`<p>Berat: ${fmt(e.weight)} gram</p>`:''}${e.trayOut?`<p>Tray keluar: ${fmt(e.trayOut)} pcs</p>`:''}${e.trayIn?`<p>Tray masuk: ${fmt(e.trayIn)} pcs</p>`:''}${e.trayBought?`<p>Tray dibeli: ${fmt(e.trayBought)} pcs</p>`:''}${e.revenue!==undefined?`<p>Total: ${money(e.revenue)}</p><p>Dibayar: ${money(e.paid||0)}</p><p>Sisa bon: ${money(e.debt||0)}</p>`:''}${e.amount!==undefined?`<p>Nominal: ${money(e.amount)}</p>`:''}<p>${h(e.note||'')}</p><div class="divider"></div><p style="text-align:center">Terima kasih</p></div><div class="form-actions no-print"><button class="secondary" id="shareReceipt">Bagikan WhatsApp</button><button class="primary" id="printReceipt">Cetak / simpan PDF</button></div>`);$('printReceipt').onclick=()=>window.print();$('shareReceipt').onclick=()=>{let text=`CANGKANG MAS\n${e.label||e.type}\nTanggal: ${e.date}\nCustomer: ${e.partyName||'Pembeli umum'}\n${e.productName||''} ${e.weight?fmt(e.weight)+' gram':''}\n${e.trayOut?'Tray keluar '+e.trayOut+' pcs':''}\n${e.revenue!==undefined?'Total: '+money(e.revenue)+'\nDibayar: '+money(e.paid||0)+'\nSisa: '+money(e.debt||0):''}\nTerima kasih.`;window.open('https://wa.me/?text='+encodeURIComponent(text),'_blank','noopener')}}
// Seluruh operasi yang mengubah stok atau bon menggunakan transaksi Firestore atomik.
// Biaya per gram disimpan sebagai numerator cost per 1.000 gram (base=1000).
async function recordPurchase(){let id=val('bProduct'),p=product(id),c=contact(val('bSupplier')),qty=$('bActualSwitch').checked?nval('bActual'):nval('bBundle')*nval('bCount'),price=nval('bPrice'),trayOut=nval('bTrayOut'),trayIn=nval('bTrayIn'),trayBought=nval('bTrayBought'),trayPrice=nval('bTrayPrice'),extra=nval('bCost'),date=val('bDate');if(!p||!qty||!date)throw Error('Jenis telur, tanggal dan berat harus diisi.');if(trayBought+trayIn>trayOut)throw Error('Jumlah tray ditukar + dibeli tidak boleh melebihi tray diterima.');let eggCost=Math.round(qty*price/1000),amount=eggCost+trayBought*trayPrice+extra,ref=path('products',id),tref=path('meta','tray'),cref=c?path('contacts',c.id):null,eref=entryRef();await runTransaction(db,async tx=>{let [ps,ts,cs]=await Promise.all([tx.get(ref),tx.get(tref),cref?tx.get(cref):Promise.resolve(null)]);let pd=ps.data(),td=ts.exists()?ts.data():{available:0,broken:0,unitCost:0},cd=cs?.data();if((td.available||0)<trayIn)throw Error('Tray layak fisik tidak cukup untuk ditukar.');if(trayOut>trayBought+trayIn&&!c)throw Error('Pilih supplier untuk mencatat tray yang belum ditukar atau dibeli.');let lots=[...(pd.lots||[]),{qty,cost:price+Math.round(extra*1000/qty),base:1000,at:now()}];tx.update(ref,{lots,updatedAt:now()});let available=td.available-trayIn+trayOut,unitCost=trayBought>0?Math.round(((td.available||0)*(td.unitCost||0)+trayBought*trayPrice)/((td.available||0)+trayBought)):td.unitCost||0;tx.set(tref,{...td,available,unitCost});if(cref)tx.update(cref,{trayDue:(cd.trayDue||0)+trayOut-trayIn-trayBought});tx.set(eref,{type:'purchase',label:'Kulak '+p.name,productId:id,productName:p.name,partyId:c?.id||'',partyName:c?.name||'',date,weight:qty,price,amount,eggCost,extra,trayOut,trayIn,trayBought,trayPrice,note:val('bNote'),createdAt:now()})})}
async function recordSale(){let p=product(val('sProduct')),c=contact(val('sCustomer')),qty=nval('sWeight'),date=today(),mode=val('sTrayMode'),channel=val('sChannel'),shopee=channel==='shopee',out=mode==='none'?0:nval('sTrayOut'),incoming=['swap','mixed'].includes(mode)?nval('sTrayIn'):0,bought=['buy','mixed'].includes(mode)?nval('sTrayBuy'):0,tPrice=bought?nval('sTrayPrice'):0,delivery=shopee?0:nval('sDelivery'),extra=nval('sCost'),pay=shopee?'cash':val('sPay'),unitPrice=nval('sPrice');if(!p||!qty)throw Error('Tambahkan jenis telur di menu Stok, lalu isi berat jual yang valid.');if(!shopee&&!unitPrice)throw Error('Isi harga jual per kg.');if(bought>out)throw Error('Tray dibeli tidak boleh melebihi tray keluar.');if(mode==='buy'&&bought!==out)throw Error('Untuk pembelian tray, jumlah dibeli harus sama dengan tray keluar.');if(['swap','mixed'].includes(mode)&&incoming>out)throw Error('Tray diterima melebihi tray keluar. Catat pengembalian kelebihan tray melalui menu Tray.');if(mode==='loan'&&incoming+bought)throw Error('Pinjaman tray tidak boleh sekaligus ditukar atau dibeli.');if(mode==='swap'&&bought)throw Error('Untuk tukar tray, jumlah dibeli harus 0.');if(!c&&(pay==='credit'||(out-incoming-bought)>0))throw Error('Pilih customer untuk bon atau tray yang belum dikembalikan.');if(shopee&&nval('sNet')<=0)throw Error('Isi uang bersih Shopee yang diterima.');let eggRevenue=shopee?nval('sNet'):Math.round(qty*unitPrice/1000)+delivery,revenue=eggRevenue+bought*tPrice,paid=pay==='credit'?nval('sPaid'):revenue,debt=revenue-paid;if(paid>revenue)throw Error('Pembayaran tidak boleh melebihi total.');let pref=path('products',p.id),tref=path('meta','tray'),cref=c?path('contacts',c.id):null,eref=entryRef();await runTransaction(db,async tx=>{let [ps,ts,cs]=await Promise.all([tx.get(pref),tx.get(tref),cref?tx.get(cref):Promise.resolve(null)]);let pd=ps.data(),td=ts.exists()?ts.data():{available:0,broken:0,unitCost:0},cd=cs?.data();let fifo=costFIFO(pd,qty);if(out>(td.available||0))throw Error('Tray tidak cukup. Stok tersedia '+fmt(td.available||0)+' pcs.');let trayCost=bought*(td.unitCost||0),profit=revenue-fifo.cost-trayCost-extra;tx.update(pref,{lots:fifo.lots,updatedAt:now()});tx.set(tref,{...td,available:td.available-out+incoming});if(cref)tx.update(cref,{trayDue:(cd.trayDue||0)+out-incoming-bought,debt:(cd.debt||0)+debt});tx.set(eref,{type:'sale',label:'Jual '+p.name,productId:p.id,productName:p.name,partyId:c?.id||'',partyName:c?.name||'',date,weight:qty,channel,price:unitPrice,eggRevenue,delivery,revenue,paid,debt,pay,cogs:fifo.cost+trayCost,cost:extra,profit,trayMode:mode,trayOut:out,trayIn:incoming,trayBought:bought,trayPrice:tPrice,note:val('sNote'),createdAt:now()})})}
async function recordTray(){let mode=val('tMode'),c=contact(val('tParty')),out=nval('tOut'),incoming=nval('tIn'),price=nval('tPrice'),pay=val('tPay'),date=val('tDate');if(!date)throw Error('Tanggal wajib diisi.');if(!incoming&&!out)throw Error('Isi jumlah tray masuk atau keluar.');if(['loan','return','swap'].includes(mode)&&!c)throw Error('Pilih customer atau supplier.');if(mode==='buy'&&(!incoming||out))throw Error('Kulak tray: isi tray masuk, tray keluar harus 0.');if(mode==='loan'&&(!out||incoming))throw Error('Pinjam tray: isi tray keluar saja.');if(mode==='return'&&(!incoming||out))throw Error('Pengembalian tray: isi tray masuk saja.');if(mode==='sell'&&(!out||incoming))throw Error('Penjualan tray: isi tray keluar saja.');if(mode==='broken'&&(!out||incoming))throw Error('Tray rusak: isi tray keluar saja.');if(mode==='replace'&&(!out||!incoming))throw Error('Penukaran tray rusak: isi tray rusak keluar dan tray pengganti masuk.');let tref=path('meta','tray'),cref=c?path('contacts',c.id):null,eref=entryRef(),amount=mode==='buy'?incoming*price:mode==='sell'?out*price:0,paid=mode==='sell'&&pay==='credit'?nval('tPaid'):amount;if(paid>amount)throw Error('Pembayaran melebihi tagihan.');if(mode==='sell'&&pay==='credit'&&!c)throw Error('Pilih customer untuk penjualan bon.');await runTransaction(db,async tx=>{let [ts,cs]=await Promise.all([tx.get(tref),cref?tx.get(cref):Promise.resolve(null)]);let td=ts.exists()?ts.data():{available:0,broken:0,unitCost:0},cd=cs?.data(),broken=td.broken||0,available=td.available||0;if(mode==='replace'){if(out>broken)throw Error('Stok tray rusak tidak cukup.')}else if(out>available)throw Error('Tray layak tidak cukup.');let nextAvailable=mode==='replace'?available+incoming:available-out+incoming,nextBroken=mode==='replace'?broken-out:mode==='broken'?broken+out:broken,unitCost=td.unitCost||0;if(mode==='buy')unitCost=Math.round((available*unitCost+incoming*price)/(available+incoming));tx.set(tref,{...td,available:nextAvailable,broken:nextBroken,unitCost});if(cref&&['loan','return','swap','sell'].includes(mode)){let delta=mode==='sell'?0:out-incoming;if(mode==='return'&&incoming>(cd.trayDue||0))throw Error('Tray dikembalikan melebihi saldo kewajiban pihak ini.');tx.update(cref,{trayDue:(cd.trayDue||0)+delta,debt:(cd.debt||0)+(mode==='sell'?amount-paid:0)})}let profit=mode==='sell'?amount-out*(td.unitCost||0):mode==='broken'?-out*(td.unitCost||0):0;tx.set(eref,{type:'tray',label:({buy:'Kulak tray',sell:'Jual tray',loan:'Pinjam tray',return:'Tray kembali',swap:'Tukar tray',broken:'Tray rusak',replace:'Tukar tray rusak'})[mode],date,partyId:c?.id||'',partyName:c?.name||'',trayOut:out,trayIn:incoming,price,amount,revenue:mode==='sell'?amount:0,paid,debt:amount-paid,cogs:mode==='sell'?out*(td.unitCost||0):0,profit,channel:'offline',note:val('tNote'),createdAt:now()})})}
async function recordReturn(){let direction=val('rDirection'),c=contact(val('rParty')),p=product(val('rProduct')),qty=nval('rWeight'),resolution=val('rResolution'),refund=nval('rRefund'),date=val('rDate');if(!p||!qty)throw Error('Isi jenis dan berat telur yang diretur.');if(direction!=='internal'&&(!c||c.kind!==direction))throw Error('Pilih pihak yang sesuai asal retur.');if(direction==='internal'&&resolution!=='none')throw Error('Telur busuk internal tidak memiliki pihak pengganti. Pilih tanpa penggantian.');if(resolution==='refund'&&!refund)throw Error('Masukkan nilai penggantian uang.');let pref=path('products',p.id),cref=c?path('contacts',c.id):null,eref=entryRef();await runTransaction(db,async tx=>{let [ps,cs]=await Promise.all([tx.get(pref),cref?tx.get(cref):Promise.resolve(null)]);let pd=ps.data(),cd=cs?.data(),cogs=0;if(direction!=='customer'){let fifo=costFIFO(pd,qty);cogs=fifo.cost;tx.update(pref,{lots:fifo.lots,updatedAt:now()})}if(cref&&resolution!=='none')tx.update(cref,resolution==='replace'?{eggDue:(cd.eggDue||0)+qty}:{refundDue:(cd.refundDue||0)+refund});tx.set(eref,{type:'return',label:direction==='customer'?'Retur dari customer':direction==='supplier'?'Retur ke supplier':'Telur busuk gudang',date,partyId:c?.id||'',partyName:c?.name||'',productId:p.id,productName:p.name,weight:qty,direction,resolution,refund,cogs,profit:direction==='customer'?-(resolution==='refund'?refund:0):-cogs,channel:'shared',note:val('rNote'),createdAt:now()})})}
async function recordAdjust(){let p=product(val('aProduct')),actual=nval('aStock'),reason=val('aReason').trim(),price=nval('aCost');if(!p||!reason)throw Error('Pilih jenis telur dan isi alasan.');let pref=path('products',p.id),eref=entryRef();await runTransaction(db,async tx=>{let ps=await tx.get(pref),pd=ps.data(),current=stock(pd),delta=actual-current;if(delta>0&&!price)throw Error('Isi modal per kg untuk menambah stok.');let lots=pd.lots||[],cost=0;if(delta<0){let f=costFIFO(pd,-delta);lots=f.lots;cost=f.cost}else if(delta>0)lots=[...lots,{qty:delta,cost:price,base:1000,at:now()}];tx.update(pref,{lots,updatedAt:now()});tx.set(eref,{type:'adjust',label:'Koreksi stok '+p.name,date:today(),productId:p.id,productName:p.name,weight:Math.abs(delta),delta,cogs:cost,profit:-cost,channel:'shared',note:reason,createdAt:now()})})}
async function recordSettlement(id){let c=contact(id),mode=val('qMode'),amount=nval('qAmount');if(!amount)throw Error('Jumlah harus lebih dari 0.');if(mode==='debt'&&c.kind!=='customer')throw Error('Bon hanya untuk customer.');if(mode==='debt'&&amount>(c.debt||0))throw Error('Nominal lebih besar daripada sisa bon.');if(mode==='refund'&&amount>(c.refundDue||0))throw Error('Nominal lebih besar daripada saldo penggantian uang.');if(mode==='egg'&&amount>(c.eggDue||0))throw Error('Berat melebihi sisa hak/kewajiban telur.');let replaceProduct=mode==='egg'&&c.kind==='customer'?product(val('qProduct')):null;if(mode==='egg'&&c.kind==='supplier')throw Error('Masukkan telur pengganti supplier melalui Kulak Telur dengan modal Rp0; penyelesaian hak supplier perlu diverifikasi di riwayat sebelum ditutup.');if(mode==='egg'&&!replaceProduct)throw Error('Pilih jenis telur pengganti.');let cref=path('contacts',id),eref=entryRef(),pref=replaceProduct?path('products',replaceProduct.id):null;await runTransaction(db,async tx=>{let [cs,ps]=await Promise.all([tx.get(cref),pref?tx.get(pref):Promise.resolve(null)]),cd=cs.data(),fieldName=mode==='debt'?'debt':mode==='refund'?'refundDue':'eggDue';if(amount>(cd[fieldName]||0))throw Error('Saldo sudah berubah. Muat ulang dan coba lagi.');let replacementCost=0;if(pref){let f=costFIFO(ps.data(),amount);replacementCost=f.cost;tx.update(pref,{lots:f.lots,updatedAt:now()})}tx.update(cref,{[fieldName]:cd[fieldName]-amount});tx.set(eref,{type:'settlement',label:mode==='debt'?'Pembayaran bon':mode==='refund'?'Penyelesaian uang retur':'Pengiriman telur pengganti',date:today(),partyId:id,partyName:c.name,productId:replaceProduct?.id||'',productName:replaceProduct?.name||'',amount:mode==='egg'?0:amount,weight:mode==='egg'?amount:0,cogs:replacementCost,profit:-replacementCost,pay:val('qPay'),channel:'shared',note:val('qNote'),createdAt:now()})})}
function exportCSV(){let es=state.entries.filter(e=>e.date?.startsWith(selectedMonth)),rows=[['Tanggal','Jenis','Pihak','Saluran','Produk','Gram','Tray Keluar','Tray Masuk','Pendapatan','HPP','Biaya','Laba','Catatan'],...es.map(e=>[e.date,e.label,e.partyName,e.channel,e.productName,e.weight,e.trayOut,e.trayIn,e.revenue,e.cogs,e.cost,e.profit,e.note])];download('cangkang-mas-'+selectedMonth+'.csv','\ufeff'+rows.map(r=>r.map(x=>'"'+String(x??'').replaceAll('"','""')+'"').join(';')).join('\r\n'),'text/csv;charset=utf-8')}
function exportJSON(){download('cangkang-mas-backup-'+today()+'.json',JSON.stringify({exportedAt:now(),products:state.products,contacts:state.contacts,entries:state.entries,tray:state.tray},null,2),'application/json')}
function download(name,body,mime){let url=URL.createObjectURL(new Blob([body],{type:mime})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1500)}
// Jalankan inisialisasi sekali pada setiap pembukaan halaman. Firebase menyimpan sesi
// anonim secara lokal, sehingga reload tidak membuat akun baru selama sesi masih ada.
let startupPromise;
async function startApp(){
  if(startupPromise)return startupPromise;
  startupPromise=(async()=>{
    if(firebaseConfig.apiKey.startsWith('ISI_') || firebaseConfig.projectId.startsWith('ISI_'))
      throw Error('Firebase belum dikonfigurasi. Isi firebase-config.js.');
    firebase=initializeApp(firebaseConfig);
    auth=getAuth(firebase);
    db=getFirestore(firebase);
    await setPersistence(auth,browserLocalPersistence);
    // Tunggu pemulihan sesi dari penyimpanan browser sebelum memutuskan membuat akun.
    await auth.authStateReady();
    let user=auth.currentUser;
    if(!user){
      const previousUid=localStorage.getItem('cm-anonymous-uid');
      if(previousUid){
        throw Error('Sesi anonim lama tidak tersedia di browser ini. Jangan membuat akun baru: data lama bisa tidak terlihat. Gunakan browser semula atau pulihkan akses terlebih dahulu. UID sebelumnya: '+previousUid);
      }
      const result=await signInAnonymously(auth);
      user=result.user;
    }
    if(!user?.isAnonymous)throw Error('Sesi Firebase bukan akun anonim. Periksa pengaturan autentikasi.');
    const previousUid=localStorage.getItem('cm-anonymous-uid');
    if(previousUid && previousUid!==user.uid)
      throw Error('Identitas anonim browser berubah. UID lama: '+previousUid+'. Data lama tidak otomatis berpindah.');
    localStorage.setItem('cm-anonymous-uid',user.uid);
    $('loading').hidden=true;
    $('app').hidden=false;
    watchers();
    console.info('Cangkang Mas: sesi anonim digunakan kembali. UID:',user.uid);
  })();
  return startupPromise;
}
startApp().catch(err=>{
  $('app').hidden=true;
  $('loading').hidden=false;
  $('loadingMessage').textContent='Tidak dapat membuka aplikasi: '+(err.message||String(err));
  console.error('Cangkang Mas startup:',err);
});
