import {initializeApp} from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-app.js';
import {getAuth,signInWithEmailAndPassword,signOut,setPersistence,browserLocalPersistence,onAuthStateChanged} from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-auth.js';
import {getFirestore,doc,collection,getDocsFromServer,onSnapshot,runTransaction} from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-firestore.js';
import {firebaseConfig} from './firebase-config.js';
import {replay,integer,fmt,rupiah} from './engine.mjs?v=cm-v2-20260924-2';
import {makeReceiptPNG,downloadReceipt,receiptFilename} from './receipt.js?v=cm-v2-20260924-2';
const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;','\'':'&#39;'}[c]));
const today=()=>{const d=new Date(),offset=d.getTimezoneOffset();return new Date(d.getTime()-offset*60000).toISOString().slice(0,10)};
let auth,db,unsub,uid='',events=[],calc=replay([]),view='dashboard',modalAction=null,busy=false,loaded=false,month=today().slice(0,7),channel='all';
const newId=()=>globalThis.crypto.randomUUID?.()||Array.from(globalThis.crypto.getRandomValues(new Uint8Array(16)),b=>b.toString(16).padStart(2,'0')).join('');
const defaultDate=()=>today(), kindNames={product:'Jenis telur',contact:'Customer / supplier',productUpdate:'Perubahan jenis telur',contactUpdate:'Perubahan customer',initial:'Stok / saldo awal',purchase:'Kulak telur',sale:'Jual telur',tray:'Transaksi tray',return:'Retur telur',settlement:'Bayar bon / penggantian',expense:'Biaya operasional',adjust:'Koreksi stok'};
const products=()=>Object.values(calc.products),contacts=()=>Object.values(calc.contacts),activeEvents=()=>events.filter(e=>!e.voided).sort((a,b)=>(b.seq||0)-(a.seq||0));
const field=(label,id,value='',options={})=>`<label class="field">${esc(label)}<input name="${esc(id)}" value="${esc(value)}" ${options.required?'required':''} ${options.type?'type="'+options.type+'"':'inputmode="numeric"'} ${options.placeholder?'placeholder="'+esc(options.placeholder)+'"':''}></label>`;
const choose=(label,id,opts,value='')=>`<label class="field">${esc(label)}<select name="${esc(id)}">${opts.map(([v,t])=>`<option value="${esc(v)}" ${String(v)===String(value)?'selected':''}>${esc(t)}</option>`).join('')}</select></label>`;
const check=(label,id,on=false)=>`<label class="check"><input type="checkbox" name="${esc(id)}" ${on?'checked':''}>${esc(label)}</label>`;
const from=(form,k)=>form.elements.namedItem(k)?.value??'', number=(form,k)=>integer(from(form,k)||'0',k), required=(condition,msg)=>{if(!condition)throw Error(msg)};
const renderOpt=(records,blank='Pilih...')=>[['',blank],...records.filter(x=>x.active!==false).map(x=>[x.id,x.name])];
const eggOptions=()=>renderOpt(products(),'Pilih jenis telur'),customerOptions=()=>renderOpt(contacts().filter(c=>c.kind==='customer'),'Pembeli umum'),supplierOptions=()=>renderOpt(contacts().filter(c=>c.kind==='supplier'),'Pilih supplier');
const partyOptions=()=>renderOpt(contacts(),'Pilih pihak');
const help=(str)=>`<p class="hint">${esc(str)}</p>`;
const show=(msg,error=false)=>{let n=$('notice');n.textContent=msg;n.className='notice show'+(error?' error':'');clearTimeout(show.timer);show.timer=setTimeout(()=>n.className='notice',6500)};
const modal=(title,html)=>{$('modalTitle').textContent=title;$('modalBody').innerHTML=html;$('modal').hidden=false};
const close=()=>{if(busy)return;$('modal').hidden=true;$('modalBody').innerHTML=''};
$('modalClose').onclick=close;$('modal').addEventListener('click',e=>{if(e.target===$('modal'))close()});
const eventRef=id=>doc(db,'users',uid,'events',id),revisionRef=()=>doc(db,'users',uid,'meta','revision');
function normalized(s){return s.docs.map(d=>({id:d.id,...d.data()}))}
async function commit(action,id,type,date,data,reason=''){
 if(busy)return;busy=true;const form=$('editForm'),button=form?.querySelector('[type=submit]');if(button){button.disabled=true;button.textContent='Memeriksa & menyimpan...'}
 try{
  required(uid&&auth.currentUser?.uid===uid,'Sesi belum siap. Masuk kembali.');
  const snap=await getDocsFromServer(collection(db,'users',uid,'events')),current=normalized(snap),old=current.find(x=>x.id===id);
  if(action==='add'&&old){if(!old.voided&&old.type===type&&old.date===date&&JSON.stringify(old.data)===JSON.stringify(data)){busy=false;close();show('Transaksi ini sudah tersimpan. Tidak dibuat dua kali.');return;}throw Error('Transaksi sudah ada; tidak disimpan ulang agar tidak ganda. Buka Kelola Data jika perlu koreksi.');}
  const candidate={id,type,date,data,seq:old?.seq||0,voided:false,label:kindNames[type]};
  if(action!=='add'){required(old&&!old.voided,'Data tidak ditemukan atau telah dibatalkan.');candidate.seq=old.seq;}
  const simulated=action==='add'?[...current,{...candidate,seq:Math.max(0,...current.map(e=>e.seq||0))+1}]:current.map(e=>e.id!==id?e:action==='delete'?{...e,voided:true}:{...e,...candidate});
  replay(simulated); // Tolak semua koreksi yang merusak stok, FIFO, bon, tray, atau referensi.
  await runTransaction(db,async tx=>{
   const guard=await tx.get(revisionRef()),existing=await tx.get(eventRef(id)),revision=guard.exists()?guard.data().value||0:0;
   if(revision!==current.length)throw Error('Data berubah di HP/laptop lain. Tunggu sinkronisasi dan ulangi koreksi.');
   if(action==='add'){required(!existing.exists(),'Transaksi ini sudah tersimpan, tidak dibuat dua kali.');candidate.seq=revision+1;tx.set(eventRef(id),candidate)}
   else{required(existing.exists()&&!existing.data().voided,'Data sudah berubah.');required(existing.data().seq===old.seq,'Urutan data berubah.');if(action==='delete')tx.update(eventRef(id),{voided:true,voidReason:reason,voidAt:new Date().toISOString()});else tx.update(eventRef(id),{date,data,type,label:kindNames[type],lastReason:reason,updatedAt:new Date().toISOString()});}
   tx.set(revisionRef(),{value:revision+(action==='add'?1:0),updatedAt:new Date().toISOString()});
   tx.set(doc(collection(db,'users',uid,'audit')),{target:id,action,reason,before:old?{type:old.type,date:old.date,data:old.data}:null,after:action==='delete'?null:{type,date,data},at:new Date().toISOString()});
  });
  busy=false;close();show(action==='delete'?'Input salah dibatalkan.':'Data tersimpan dan seluruh saldo dihitung ulang.');
 }catch(e){show(e.message||'Gagal menyimpan.',true);console.error(e)}finally{busy=false;if(button?.isConnected){button.disabled=false;button.textContent='Simpan'}}
}
function sectionAction(action,type,id=''){
 const old=events.find(e=>e.id===id),v=old?.data||{},editing=action==='edit',date=editing?old.date:defaultDate();
 const base=`<form id="editForm"><div class="form-grid">${field('Tanggal','date',date,{type:'date',required:true})}`;
 let body='',hint='',title=kindNames[type]||type;
 const n=(label,key,req=false)=>field(label,key,fmt(v[key]??0),{required:req,placeholder:'0'});
 const productSelect=(id='productId')=>choose('Jenis telur',id,eggOptions(),v[id]||'');
 const partySelect=(kind)=>choose(kind==='supplier'?'Supplier':'Customer','partyId',kind==='supplier'?supplierOptions():kind==='customer'?customerOptions():partyOptions(),v.partyId||'');
 switch(type){
 case 'product':body=field('Nama jenis telur','name',v.name||'',{required:true,type:'text'});hint='Harga kulak diisi saat kulak. Harga jual diisi saat menjual.';break;
 case 'contact':body=choose('Jenis pihak','kind',[['customer','Customer'],['supplier','Supplier']],v.kind||'customer')+field('Nama','name',v.name||'',{required:true,type:'text'})+field('Nomor WhatsApp (opsional)','phone',v.phone||'',{type:'tel'})+field('Alamat (opsional)','address',v.address||'',{type:'text'});break;
 case 'initial':body=choose('Jenis stok / saldo awal','initialMode',[['egg','Telur'],['tray','Tray'],['debt','Bon customer / saldo tray'],['cash','Kas awal']],v.productId?'egg':v.partyId?'debt':'tray')+productSelect()+partySelect('customer')+n('Stok telur (gram)','weight')+n('Modal telur / kg (Rp)','price')+n('Tray layak (pcs)','trayAvailable')+n('Tray rusak (pcs)','trayBroken')+n('Modal tray / pcs (Rp)','trayCost')+n('Bon customer awal (Rp)','debt')+n('Tray dipinjam awal (pcs)','trayDue')+n('Saldo kas awal (Rp)','cashAmount')+choose('Jenis kas','pay',[['cash','Tunai'],['transfer','Transfer bank'],['qris','QRIS']],v.pay||'cash');hint='Isi stok awal sekali sebelum transaksi pertama. Kolom yang tidak berkaitan boleh 0.';break;
 case 'purchase':body=productSelect()+partySelect('supplier')+choose('Ukuran ikat','bundle',[['10000','10 kg'],['15000','15 kg']],String(v.bundle||10000))+n('Jumlah ikat','bundleCount')+check('Berat aktual tidak sama dengan nominal','actual',!!v.actual)+n('Berat aktual / berat kulak (gram)','weight',true)+n('Harga kulak / kg (Rp)','price',true)+n('Tray diterima dari kandang (pcs)','trayIn')+n('Tray kosong ditukar ke kandang (pcs)','trayOut')+n('Tray dibeli (pcs)','trayBought')+n('Harga tray dibeli / pcs (Rp)','trayPrice')+n('Ongkir / biaya kulak (Rp)','extra')+choose('Metode bayar kulak','pay',[['cash','Tunai'],['transfer','Transfer'],['qris','QRIS']],v.pay||'cash');hint='Jumlah tray sesuai fisik. Jika menerima 8 tray dan menyerahkan 8 tray kosong, stok tray total tidak bertambah.';break;
 case 'sale':body=choose('Saluran','channel',[['offline','Offline'],['shopee','Shopee'],['online','Online lainnya']],v.channel||'offline')+partySelect('customer')+productSelect()+n('Berat telur (gram)','weight',true)+n('Harga jual / kg (Rp)','price')+n('Uang bersih diterima Shopee (Rp)','net')+n('Tray keluar (pcs)','trayOut')+n('Tray kosong diterima (pcs)','trayIn')+n('Tray dibeli customer (pcs)','trayBought')+n('Harga jual tray / pcs (Rp)','trayPrice')+n('Ongkir ditagih customer (Rp)','delivery')+n('Biaya operasional transaksi (Rp)','extra')+choose('Pembayaran','pay',[['cash','Tunai'],['transfer','Transfer'],['qris','QRIS'],['credit','Bon / cicilan']],v.pay||'cash')+n('Dibayar sekarang (Rp) · isi 0 jika bon penuh','paid');hint='Shopee: masukkan uang bersih saja, tanpa hitung potongan. Untuk transaksi non-bon, pembayaran otomatis lunas. Satu jenis telur per nota.';break;
 case 'tray':body=choose('Perlakuan tray','mode',[['buy','Kulak tray'],['sell','Jual tray baru'],['convert','Customer membeli tray yang dipinjam'],['loan','Pinjam tray'],['return','Tray dikembalikan'],['swap','Tukar tray'],['broken','Tray rusak'],['replace','Tukar tray rusak']],v.mode||'swap')+partySelect('all')+n('Tray keluar (pcs)','out')+n('Tray masuk (pcs)','in')+n('Harga tray / pcs (Rp)','price')+choose('Pembayaran','pay',[['cash','Tunai'],['transfer','Transfer'],['qris','QRIS'],['credit','Bon / cicilan']],v.pay||'cash')+n('Dibayar sekarang jika bon (Rp)','paid');break;
 case 'return':body=choose('Saluran retur jika tanpa nota asal','channel',[['shared','Belum ditentukan / bersama'],['offline','Offline'],['shopee','Shopee'],['online','Online lainnya']],v.channel||'shared')+choose('Nota penjualan asal (khusus retur customer)','invoiceId',[["",'Tanpa nota asal / retur lain'],...Object.values(calc.invoices).filter(i=>!i.opening&&!i.traySale).map(i=>[i.id,i.date+' · '+(calc.contacts[i.partyId]?.name||'Pembeli umum')+' · '+fmt(i.weight)+' gram'])],v.invoiceId||'')+choose('Asal retur','direction',[['customer','Dari customer'],['supplier','Ke supplier'],['internal','Busuk di gudang']],v.direction||'customer')+partySelect('all')+productSelect()+n('Berat telur busuk (gram)','weight',true)+choose('Penyelesaian','resolution',[['none','Tanpa penggantian'],['refund','Ganti uang'],['replace','Ganti telur berikutnya']],v.resolution||'none')+n('Nominal penggantian uang (Rp)','refund');hint='Untuk retur customer, stok telur sudah berkurang saat jual; jangan mengurangi stok yang sama lagi.';break;
 case 'settlement':body=partySelect('all')+choose('Penyelesaian','mode',[['debt','Bayar bon nota'],['refund','Pengembalian uang retur'],['egg','Penggantian telur']],v.mode||'debt')+choose('Nota yang dibayar','invoiceId',[["",'Pilih nota bon'],...Object.values(calc.invoices).filter(i=>i.debt>0).map(i=>[i.id,i.date+' · '+rupiah(i.debt)])],v.invoiceId||'')+choose('Retur yang diselesaikan','claimId',[["",'Pilih retur belum selesai'],...Object.values(calc.claims).filter(c=>c.eggDue>0||c.refundDue>0).map(c=>[c.id,'Retur '+(calc.contacts[c.partyId]?.name||'')+' · '+(c.eggDue>0?fmt(c.eggDue)+' gram':rupiah(c.refundDue))])],v.claimId||'')+productSelect()+n('Nominal pembayaran / refund (Rp)','amount')+n('Berat telur pengganti (gram)','weight')+choose('Metode pembayaran','pay',[['cash','Tunai'],['transfer','Transfer'],['qris','QRIS']],v.pay||'cash');hint='Pembayaran bon mengurangi sisa nota yang dipilih; tidak menambah omzet.';break;
 case 'expense':body=choose('Saluran biaya','channel',[['offline','Offline'],['shopee','Shopee'],['online','Online lainnya'],['shared','Biaya bersama']],v.channel||'shared')+field('Keterangan biaya','name',v.name||'',{type:'text',required:true})+n('Nominal biaya (Rp)','amount',true)+choose('Dibayar melalui','pay',[['cash','Tunai'],['transfer','Transfer'],['qris','QRIS']],v.pay||'cash');break;
 case 'adjust':body=choose('Jenis koreksi','adjustMode',[['egg','Stok telur fisik'],['tray','Stok tray fisik']],v.productId?'egg':'tray')+productSelect()+n('Stok telur fisik (gram)','actual')+n('Modal / kg bila stok bertambah','price')+n('Stok tray layak (pcs)','trayAvailable')+n('Stok tray rusak (pcs)','trayBroken')+n('Modal tray / pcs (Rp)','trayCost');hint='Koreksi stok fisik hanya untuk hasil opname, bukan untuk membetulkan transaksi salah input. Gunakan Kelola Data untuk kesalahan input.';break;
 default:show('Kategori belum tersedia.',true);return;
 }
 const reason=editing?field('Alasan koreksi input','reason','',{type:'text',required:true}):'';
 modal((editing?'Edit ':'Input ')+title,base+body+reason+`</div>${help(hint)}<div class="summary" id="formPreview">Perhitungan akan divalidasi sebelum disimpan.</div><div class="form-actions"><button class="primary" type="submit">Simpan</button></div></form>`);
 const form=$('editForm');
 form.addEventListener('blur',event=>{const el=event.target;if(el instanceof HTMLInputElement&&el.inputMode==='numeric'&&el.value.trim()){try{el.value=fmt(integer(el.value,el.name));}catch{show('Gunakan angka bulat, titik hanya untuk ribuan. Contoh: 30.000',true)}}},true);
 form.oninput=()=>{if(type==='purchase'){const bundle=Number(from(form,'bundle'))||10000,count=(()=>{try{return number(form,'bundleCount')}catch{return 0}})();if(!form.elements.namedItem('actual').checked)form.elements.namedItem('weight').value=fmt(bundle*count)};updateFormUI();updatePreview()};
 if(type==='purchase'&&!editing){form.elements.namedItem('bundleCount').value='1';form.elements.namedItem('weight').value=fmt(Number(from(form,'bundle')))}
 if(type==='sale'){const p=form.elements.namedItem('productId');p.onchange=()=>{const s=calc.products[p.value];if(s&&!editing)form.elements.namedItem('price').value=fmt(s.lastPrice||0);updatePreview()};}
 if(type==='return'){form.elements.namedItem('invoiceId').onchange=()=>{const invoice=calc.invoices[from(form,'invoiceId')];if(invoice){form.elements.namedItem('partyId').value=invoice.partyId;form.elements.namedItem('productId').value=invoice.productId;}updateFormUI();updatePreview()};}
 if(type==='settlement'){form.elements.namedItem('claimId').onchange=()=>{const claim=calc.claims[from(form,'claimId')];if(claim){form.elements.namedItem('partyId').value=claim.partyId;form.elements.namedItem('productId').value=claim.productId;if(from(form,'mode')==='refund')form.elements.namedItem('amount').value=fmt(claim.refundDue);else form.elements.namedItem('weight').value=fmt(claim.eggDue)}updateFormUI()};form.elements.namedItem('mode').onchange=()=>form.elements.namedItem('partyId').dispatchEvent(new Event('change'));form.elements.namedItem('partyId').onchange=()=>{const cId=from(form,'partyId');const select=form.elements.namedItem('invoiceId');select.innerHTML='<option value="">Pilih nota bon</option>'+Object.values(calc.invoices).filter(i=>i.partyId===cId&&i.debt>0).map(i=>`<option value="${esc(i.id)}">${esc(i.date)} · ${rupiah(i.debt)}</option>`).join('');const claim=form.elements.namedItem('claimId');claim.innerHTML='<option value="">Pilih retur</option>'+Object.values(calc.claims).filter(x=>x.partyId===cId&&(from(form,'mode')==='refund'?x.refundDue>0:x.eggDue>0)).map(x=>`<option value="${esc(x.id)}">${x.eggDue>0?fmt(x.eggDue)+' gram':rupiah(x.refundDue)}</option>`).join('');};}
 updateFormUI();updatePreview();
 function updateFormUI(){
  const showField=(key,visible)=>{const element=form.elements.namedItem(key);if(element){const wrap=element.closest('label');if(wrap)wrap.hidden=!visible}};
  if(type==='initial'){const m=from(form,'initialMode');for(const k of ['productId','weight','price'])showField(k,m==='egg');for(const k of ['trayAvailable','trayBroken','trayCost'])showField(k,m==='tray');for(const k of ['partyId','debt','trayDue'])showField(k,m==='debt');showField('cashAmount',m==='cash');showField('pay',m==='cash');}
  if(type==='purchase'){showField('weight',form.elements.namedItem('actual').checked);showField('trayPrice',number(form,'trayBought')>0);}
  if(type==='sale'){const shopee=from(form,'channel')==='shopee',out=number(form,'trayOut'),buy=number(form,'trayBought');showField('price',!shopee);showField('net',shopee);showField('delivery',!shopee);showField('pay',!shopee);showField('paid',!shopee&&from(form,'pay')==='credit');for(const k of ['trayIn','trayBought'])showField(k,out>0);showField('trayPrice',out>0&&buy>0);}
  if(type==='tray'){const m=from(form,'mode'),pay=from(form,'pay');showField('partyId',['sell','convert','loan','return','swap','buy'].includes(m));showField('out',!['buy','return'].includes(m));showField('in',['buy','return','swap','replace'].includes(m));showField('price',['buy','sell','convert'].includes(m));showField('pay',['buy','sell','convert'].includes(m));showField('paid',['sell','convert'].includes(m)&&pay==='credit');}
  if(type==='return'){const direction=from(form,'direction');showField('partyId',direction!=='internal');showField('invoiceId',direction==='customer');showField('channel',direction==='customer'&&!from(form,'invoiceId'));showField('resolution',direction!=='internal');showField('refund',direction!=='internal'&&from(form,'resolution')==='refund');}
  if(type==='settlement'){const mode=from(form,'mode');showField('invoiceId',mode==='debt');showField('claimId',mode!=='debt');showField('productId',false);showField('amount',mode!=='egg');showField('weight',mode==='egg');showField('pay',mode!=='egg');}
  if(type==='adjust'){const mode=from(form,'adjustMode');for(const k of ['productId','actual','price'])showField(k,mode==='egg');for(const k of ['trayAvailable','trayBroken','trayCost'])showField(k,mode==='tray');}
 }
 function updatePreview(){try{if(type==='sale'){const w=number(form,'weight'),p=number(form,'price'),b=number(form,'trayBought'),tp=number(form,'trayPrice'),ship=number(form,'delivery'),net=number(form,'net'),shopee=from(form,'channel')==='shopee';$('formPreview').textContent='Perkiraan total tagihan: '+rupiah(shopee?net:Math.round(w*p/1000)+b*tp+ship)+' · Stok: '+fmt(calc.stock[from(form,'productId')]||0)+' gram'}else if(type==='purchase'){$('formPreview').textContent='Berat masuk: '+fmt(number(form,'weight'))+' gram · Tray tersedia: '+fmt(calc.tray.available)+' pcs'}else $('formPreview').textContent='Sistem memeriksa dampak perubahan pada seluruh transaksi saat disimpan.'}catch{$('formPreview').textContent='Masukkan angka bulat; titik hanya untuk ribuan.'}}
 form.onsubmit=e=>{e.preventDefault();try{
   const idToSave=editing?id:(form.dataset.operationId ||= newId()),d=from(form,'date');required(d,'Tanggal wajib.');
   const data={};for(const el of [...form.elements]){if(!el.name||['date','reason'].includes(el.name))continue;if(el.type==='checkbox')data[el.name]=el.checked;else if(el.tagName==='SELECT'||['name','kind','phone','address','direction','resolution','mode','channel','pay','invoiceId','productId','partyId','bundle','adjustMode','initialMode'].includes(el.name))data[el.name]=el.value;else data[el.name]=integer(el.value||'0',el.name);}
   if(type==='sale'){if(data.trayOut===0){data.trayIn=0;data.trayBought=0;data.trayPrice=0;}if(data.channel==='shopee'){required(data.net>0,'Masukkan uang bersih Shopee.');data.paid=data.net;data.delivery=0;data.pay='cash'}else if(data.pay!=='credit'){const total=Math.round(data.weight*data.price/1000)+data.delivery+data.trayBought*data.trayPrice;data.paid=total;}required(data.weight>0,'Berat penjualan wajib diisi.');}
   if(type==='purchase'){required(data.weight>0&&data.price>0,'Isi berat dan harga kulak.');}
   if(type==='tray'){if(['buy','return'].includes(data.mode))data.out=0;if(!['buy','return','swap','replace'].includes(data.mode))data.in=0;if(!['buy','sell','convert'].includes(data.mode))data.price=0;if(data.pay!=='credit')data.paid=data.out*data.price;}
   if(type==='initial'){if(data.initialMode==='egg'){data.partyId='';delete data.trayAvailable;delete data.trayBroken;delete data.cashAmount;}else if(data.initialMode==='tray'){data.productId='';data.partyId='';delete data.weight;delete data.debt;delete data.trayDue;delete data.cashAmount;}else if(data.initialMode==='debt'){data.productId='';delete data.trayAvailable;delete data.trayBroken;delete data.weight;delete data.cashAmount;}else{data.productId='';data.partyId='';delete data.trayAvailable;delete data.trayBroken;delete data.weight;delete data.debt;delete data.trayDue;delete data.cashAmount;}}
   if(type==='adjust'){if(data.adjustMode==='egg'){delete data.trayAvailable;delete data.trayBroken;delete data.trayCost;}else data.productId='';}
   if(type==='settlement'){if(data.mode==='egg'){data.amount=0;const claim=calc.claims[data.claimId];if(claim)data.productId=claim.productId;}if(data.mode==='debt')required(data.invoiceId,'Pilih nota yang dibayar.');else required(data.claimId,'Pilih retur yang diselesaikan.');}
   if(type==='return'&&data.direction==='internal'){data.partyId='';data.resolution='none';data.invoiceId='';}if(type==='return'&&data.direction==='supplier')data.invoiceId='';
   commit(editing?'edit':'add',idToSave,type,d,data,editing?from(form,'reason'):'');
 }catch(error){show(error.message,true)}};
}
function deleteForm(id){const e=events.find(x=>x.id===id);if(!e)return;modal('Batalkan input salah',`<p><b>${esc(kindNames[e.type]||e.type)}</b> · ${esc(e.date)}. Penghapusan membatalkan dampak transaksi, tetapi menyimpan jejak audit.</p><form id="deleteForm">${field('Alasan pembatalan','reason','',{required:true,type:'text'})}${check('Saya yakin ini input yang salah','confirmed')}<div class="form-actions"><button class="danger-btn" type="submit">Batalkan input ini</button></div></form>`);$('deleteForm').onsubmit=ev=>{ev.preventDefault();const f=ev.target;try{required(f.elements.namedItem('confirmed').checked,'Centang konfirmasi.');required(from(f,'reason').trim(),'Isi alasan.');commit('delete',id,e.type,e.date,e.data,from(f,'reason').trim())}catch(err){show(err.message,true)}}}
function record(e){const o=calc.outcomes[e.id]||{},v=e.data||{},name=calc.products[v.productId]?.name||v.name||kindNames[e.type]||e.type,party=calc.contacts[v.partyId]?.name||'';return {id:e.id,type:e.type,date:e.date,label:kindNames[e.type]+' '+name,productName:name,partyName:party,channel:v.channel||'offline',weight:v.weight||0,price:v.price||0,eggRevenue:e.type==='sale'&&v.channel!=='shopee'?(o.revenue||0)-(v.trayBought||0)*(v.trayPrice||0):(o.revenue||0),revenue:o.revenue||0,paid:calc.invoices[e.id]?.paid||0,debt:calc.invoices[e.id]?.debt||0,pay:v.pay||'cash',delivery:v.delivery||0,trayBought:v.trayBought||0,trayOut:v.trayOut||0,trayIn:v.trayIn||0,trayPrice:v.trayPrice||0,trayMode:v.trayMode||((v.trayOut||0)&&!(v.trayIn||0)&&!(v.trayBought||0)?'loan':'swap'),profit:o.profit||0,amount:o.amount||0};}
async function receipt(id){const e=events.find(x=>x.id===id&&!x.voided);if(!e)return;if(e.type!=='sale'){modal('Detail',`<p>${esc(kindNames[e.type])} · ${esc(e.date)}</p><pre>${esc(JSON.stringify(e.data,null,2))}</pre>`);return}try{const blob=await makeReceiptPNG(record(e)),url=URL.createObjectURL(blob),filename=receiptFilename(record(e));modal('Nota Penjualan',`<img class="receipt-preview" id="receiptPreview" src="${url}" alt="Nota Cangkang Mas"><div class="form-actions no-print"><button id="printReceipt" class="secondary">Cetak</button><button id="downloadReceipt" class="secondary">Simpan PNG</button><button id="shareReceipt" class="primary">WhatsApp</button></div>${help('Nota dibuat di browser, tidak disimpan di Firebase.')}`);$('printReceipt').onclick=()=>window.print();$('downloadReceipt').onclick=()=>downloadReceipt(blob,filename);$('shareReceipt').onclick=async()=>{const file=new File([blob],filename,{type:'image/png'});try{if(navigator.canShare?.({files:[file]}))await navigator.share({files:[file]});else{downloadReceipt(blob,filename);show('Gambar disimpan. Pilih gambar tersebut melalui WhatsApp.')}}catch(err){if(err.name!=='AbortError')show(err.message,true)}};setTimeout(()=>URL.revokeObjectURL(url),120000)}catch(err){show('Gagal membuat nota: '+err.message,true)}}
function historyRows(items,manage=false){return items.map(e=>{const o=calc.outcomes[e.id]||{},r=record(e);return `<div class="list-row"><div><b>${esc(e.data?.name||kindNames[e.type]||e.type)}</b><small>${esc(e.date)} · ${esc(r.partyName||r.productName||'')} ${r.weight?fmt(r.weight)+' gram':''}</small></div><aside>${o.revenue?rupiah(o.revenue):o.amount?rupiah(o.amount):'—'}<small>Laba ${rupiah(o.profit||0)}</small>${manage?`<button class="secondary" data-edit="${esc(e.id)}">Edit</button> <button class="danger-btn" data-delete="${esc(e.id)}">Hapus</button>`:`<button class="outline" data-receipt="${esc(e.id)}">Detail / nota</button>`}</aside></div>`}).join('')||'<p class="empty">Belum ada data.</p>'}
function card(label,value,small=''){return `<div class="card"><span class="metric-label">${esc(label)}</span><div class="metric-value">${value}</div><p>${esc(small)}</p></div>`}
function reportFigures(){const period=Object.entries(calc.period).filter(([k])=>k.startsWith(month+'|'));const sum=filter=>period.filter(([k])=>filter(k.split('|')[1])).reduce((a,[,v])=>{for(const key of ['revenue','cogs','cost','profit'])a[key]+=v[key];return a},{revenue:0,cogs:0,cost:0,profit:0});return {all:sum(()=>true),offline:sum(c=>c==='offline'),online:sum(c=>c==='shopee'||c==='online'),shared:sum(c=>c==='shared'),shopee:sum(c=>c==='shopee')}}
function render(){if(!uid||!loaded)return;const reports=reportFigures(),stock=Object.values(calc.stock).reduce((a,b)=>a+b,0),receivable=contacts().filter(c=>c.kind==='customer').reduce((a,c)=>a+c.debt,0),trayDue=contacts().filter(c=>c.kind==='customer').reduce((a,c)=>a+c.trayDue,0);$('nav').querySelectorAll('[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===view));let html='';
 if(view==='dashboard')html=`<div class="hero"><div><span>CANGKANG MAS · ${esc(month)}</span><h2>${rupiah(reports.all.profit)}</h2><p>Laba seluruh saluran bulan ini</p></div><img class="hero-logo" src="assets/logo.png"></div><div class="grid four">${card('Stok telur',fmt(stock)+' gram')}${card('Tray fisik layak',fmt(calc.tray.available)+' pcs')}${card('Laba offline',rupiah(reports.offline.profit))}${card('Laba online',rupiah(reports.online.profit))}</div><div class="card"><h2>Transaksi cepat</h2><div class="actions">${[['purchase','Kulak telur'],['sale','Jual telur'],['tray','Tray'],['return','Retur']].map(([k,t])=>`<button class="action" data-new="${k}">${t}</button>`).join('')}</div></div><div class="grid">${card('Bon customer',rupiah(receivable))}${card('Tray di customer',fmt(trayDue)+' pcs')}</div><div class="card"><h2>Riwayat terbaru</h2>${historyRows(activeEvents().filter(e=>!['product','contact','productUpdate','contactUpdate'].includes(e.type)).slice(0,6))}</div>`;
 if(view==='sale')html=`<h1 class="page-title">Jual telur</h1><p class="subtitle">Satu jenis telur per transaksi, gram bulat, FIFO otomatis.</p><div class="card"><button class="primary" data-new="sale">+ Input penjualan</button> <button class="outline" data-new="contact">+ Customer</button></div><div class="card"><h2>Riwayat penjualan</h2>${historyRows(activeEvents().filter(e=>e.type==='sale').slice(0,15))}</div>`;
 if(view==='stock')html=`<h1 class="page-title">Persediaan</h1><div class="card"><button class="primary" data-new="product">+ Jenis telur</button> <button class="secondary" data-new="purchase">Kulak telur</button> <button class="outline" data-new="initial">Stok awal</button></div><div class="grid">${products().map(p=>card(p.name,fmt(calc.stock[p.id]||0)+' gram','Harga jual terakhir '+rupiah(p.lastPrice))).join('')}${card('Tray layak',fmt(calc.tray.available)+' pcs')}${card('Tray rusak',fmt(calc.tray.broken)+' pcs')}</div>`;
 if(view==='reports'){const t=channel==='all'?reports.all:channel==='offline'?reports.offline:channel==='online'?reports.online:channel==='shopee'?reports.shopee:reports.shared;html=`<h1 class="page-title">Laporan keuntungan</h1><div class="card"><label>Periode <input type="month" id="monthFilter" value="${esc(month)}"></label><label>Saluran <select id="channelFilter">${[['all','Semua'],['offline','Offline'],['online','Online gabungan'],['shopee','Shopee'],['shared','Biaya bersama / belum dialokasikan']].map(([k,v])=>`<option value="${k}" ${channel===k?'selected':''}>${v}</option>`).join('')}</select></label></div><div class="grid">${card('Pendapatan',rupiah(t.revenue))}${card('HPP',rupiah(t.cogs))}${card('Biaya & retur',rupiah(t.cost))}${card('Laba',rupiah(t.profit))}</div><div class="card"><h2>Ringkasan bulanan</h2>${[['Offline',reports.offline],['Online',reports.online],['Biaya bersama',reports.shared],['Total gabungan',reports.all]].map(([k,v])=>`<div class="row"><b>${k}</b><b>${rupiah(v.profit)}</b></div>`).join('<div class="divider"></div>')}<p class="hint">Biaya bersama tidak dialokasikan ke offline/online; tetap mengurangi laba gabungan. Pembayaran cicilan tidak dihitung lagi sebagai omzet.</p><div class="divider"></div><h3>Arus kas bulan ini</h3><div class="row"><span>Uang masuk (termasuk saldo awal jika dicatat)</span><b>${rupiah(calc.cash[month]?.in||0)}</b></div><div class="row"><span>Uang keluar</span><b>${rupiah(calc.cash[month]?.out||0)}</b></div><p class="hint">Arus kas berbeda dari omzet dan laba. Cicilan hanya menambah uang masuk, tidak menambah omzet baru.</p><button class="secondary" id="exportCSV">Ekspor laporan CSV</button></div>`;}
 if(view==='more')html=`<h1 class="page-title">Lainnya</h1><div class="card"><h2>Kelola Data</h2><p>Semua tombol Edit dan Hapus hanya tersedia di sini, untuk memperbaiki input yang salah.</p><button class="primary" id="manageBtn">Buka Kelola Data</button></div><div class="card"><h2>Input lainnya</h2><div class="actions">${[['purchase','Kulak telur'],['tray','Tray'],['return','Retur'],['settlement','Bayar bon / retur'],['expense','Biaya usaha'],['contact','Customer / supplier'],['product','Jenis telur'],['adjust','Stok opname'],['initial','Stok awal']].map(([k,t])=>`<button class="action" data-new="${k}">${t}</button>`).join('')}</div></div><div class="card"><h2>Customer & nota</h2>${contacts().filter(c=>c.kind==='customer').map(c=>`<div class="list-row"><div><b>${esc(c.name)}</b><small>Bon ${rupiah(c.debt)} · Tray ${fmt(c.trayDue)} pcs</small></div><button class="outline" data-customer="${esc(c.id)}">Nota / bayar</button></div>`).join('')||'Belum ada customer.'}</div><div class="card"><button class="secondary" id="backupBtn">Ekspor backup JSON</button><button class="outline" id="restoreBtn">Pulihkan backup (hanya database kosong)</button><input id="restoreInput" type="file" accept="application/json,.json" hidden></div>`;
 $('content').innerHTML=html;document.querySelectorAll('[data-new]').forEach(b=>b.onclick=()=>sectionAction('add',b.dataset.new));document.querySelectorAll('[data-receipt]').forEach(b=>b.onclick=()=>receipt(b.dataset.receipt));if($('manageBtn'))$('manageBtn').onclick=manage;if($('backupBtn'))$('backupBtn').onclick=backup;if($('restoreBtn'))$('restoreBtn').onclick=()=>$('restoreInput').click();if($('restoreInput'))$('restoreInput').onchange=e=>{const file=e.target.files?.[0];if(file)restore(file)};if($('monthFilter'))$('monthFilter').onchange=e=>{month=e.target.value;render()};if($('channelFilter'))$('channelFilter').onchange=e=>{channel=e.target.value;render()};if($('exportCSV'))$('exportCSV').onclick=csv;document.querySelectorAll('[data-customer]').forEach(b=>b.onclick=()=>customerDetail(b.dataset.customer));}
function customerDetail(id){const c=calc.contacts[id];if(!c)return;modal(c.name,`<h3>Bon ${rupiah(c.debt)} · Tray ${fmt(c.trayDue)} pcs</h3><button class="primary" id="payCustomer">Bayar bon / retur</button><h3>Nota penjualan</h3>${historyRows(activeEvents().filter(e=>e.type==='sale'&&e.data?.partyId===id))}`);$('payCustomer').onclick=()=>{sectionAction('add','settlement');$('editForm').elements.namedItem('partyId').value=id;$('editForm').elements.namedItem('partyId').dispatchEvent(new Event('change'))};document.querySelectorAll('[data-receipt]').forEach(b=>b.onclick=()=>receipt(b.dataset.receipt))}
function manage(){modal('Kelola Data · Edit & Hapus',`<p class="hint">Khusus memperbaiki input salah. Koreksi divalidasi terhadap semua transaksi menurut urutan waktu; jika stok atau saldo negatif, perubahan ditolak dan data lama tetap utuh.</p><div class="form-grid">${choose('Kategori','manageType',[['all','Semua'],...Object.entries(kindNames).map(([k,v])=>[k,v])],'all')}${field('Cari nama / tanggal / nomor','manageSearch','',{type:'text'})}</div><div id="manageResults"></div>`);const draw=()=>{const type=$('modalBody').querySelector('[name=manageType]').value,term=$('modalBody').querySelector('[name=manageSearch]').value.toLowerCase(),rows=activeEvents().filter(e=>(type==='all'||e.type===type)&&[e.id,e.date,e.data?.name,e.data?.productId,kindNames[e.type],calc.contacts[e.data?.partyId]?.name].some(s=>String(s||'').toLowerCase().includes(term)));$('manageResults').innerHTML=historyRows(rows,true);document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>sectionAction('edit',events.find(e=>e.id===b.dataset.edit).type,b.dataset.edit));document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>deleteForm(b.dataset.delete))};$('modalBody').querySelector('[name=manageType]').onchange=draw;$('modalBody').querySelector('[name=manageSearch]').oninput=draw;draw()}
function fileDownload(name,body,type){const u=URL.createObjectURL(new Blob([body],{type})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),60000)}
async function backup(){try{const snap=await getDocsFromServer(collection(db,'users',uid,'audit'));const audits=normalized(snap);fileDownload('cangkang-mas-backup-'+today()+'.json',JSON.stringify({exportedAt:new Date().toISOString(),version:2,events,audits},null,2),'application/json');show('Backup data dan riwayat koreksi berhasil dibuat. Simpan di tempat aman.')}catch(e){show('Gagal membuat backup lengkap: '+e.message,true)}}
async function restore(file){if(busy)return;try{required(file.size<3_000_000,'File backup terlalu besar untuk pemulihan satu transaksi.');const data=JSON.parse(await file.text());required(data.version===2&&Array.isArray(data.events)&&Array.isArray(data.audits),'Format backup Cangkang Mas V2 tidak sesuai.');required(data.events.length+data.audits.length<=400,'Backup terlalu banyak transaksi untuk pemulihan atomik browser. Jangan impor sebagian data.');const ids=new Set();for(const e of data.events){required(typeof e.id==='string'&&e.id.length>=8&&!e.id.includes('/')&&typeof e.type==='string'&&!ids.has(e.id),'ID transaksi backup tidak valid atau ganda.');ids.add(e.id)}for(const e of data.audits){required(typeof e.id==='string'&&e.id.length>=8&&!e.id.includes('/'),'ID audit backup tidak valid.')}replay(data.events);const existing=await getDocsFromServer(collection(db,'users',uid,'events'));required(existing.empty||existing.docs.length===0,'Database tidak kosong. Pemulihan ditolak agar tidak menggandakan transaksi.');required(confirm('Pulihkan '+data.events.length+' transaksi ke database kosong? Semua data dan riwayat koreksi pada file akan dibuat kembali.'),'Pemulihan dibatalkan.');busy=true;await runTransaction(db,async tx=>{const guard=await tx.get(revisionRef());required(!guard.exists()||(guard.data().value||0)===0,'Database pernah berisi transaksi. Jangan pulihkan tanpa memeriksa data.');for(const e of data.events)tx.set(eventRef(e.id),e);for(const a of data.audits)tx.set(doc(db,'users',uid,'audit',a.id),a);tx.set(revisionRef(),{value:data.events.length,updatedAt:new Date().toISOString()})});show('Pemulihan selesai. Tunggu sinkronisasi Dashboard.')}catch(e){show('Pemulihan tidak dilakukan: '+e.message,true);console.error(e)}finally{busy=false}}
function csv(){const rows=[['Tanggal','Kategori','Pihak','Jenis telur','Berat','Pendapatan','HPP','Biaya','Laba'],...activeEvents().filter(e=>e.date.startsWith(month)).map(e=>{const o=calc.outcomes[e.id]||{},d=e.data||{};return [e.date,kindNames[e.type],calc.contacts[d.partyId]?.name||'',calc.products[d.productId]?.name||'',d.weight||0,o.revenue||0,o.cogs||0,o.cost||0,o.profit||0]})];fileDownload('cangkang-mas-'+month+'.csv','\ufeff'+rows.map(row=>row.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(';')).join('\r\n'),'text/csv;charset=utf-8')}
$('nav').onclick=e=>{const b=e.target.closest('[data-page]');if(!b)return;view=b.dataset.page;render();window.scrollTo(0,0)};
async function boot(){const firebase=initializeApp(firebaseConfig);auth=getAuth(firebase);db=getFirestore(firebase);await setPersistence(auth,browserLocalPersistence);await auth.authStateReady();$('loading').hidden=true;onAuthStateChanged(auth,user=>{if(user&&!user.isAnonymous){if(uid===user.uid)return;uid=user.uid;unsub?.();loaded=false;events=[];$('login').hidden=true;$('app').hidden=false;$('sync').textContent='● Memuat data';unsub=onSnapshot(collection(db,'users',uid,'events'),snapshot=>{try{const incoming=normalized(snapshot);const next=replay(incoming);events=incoming;calc=next;loaded=true;$('sync').textContent=snapshot.metadata.fromCache?'● Cache lokal':'● Data Firebase';render()}catch(err){$('sync').textContent='● Periksa data';show('Data belum konsisten: '+err.message,true);console.error(err)}},err=>{$('sync').textContent='● Koneksi bermasalah';show('Gagal membaca Firebase: '+err.message,true)})}else{uid='';unsub?.();loaded=false;$('app').hidden=true;$('login').hidden=false}});$('loginForm').onsubmit=async e=>{e.preventDefault();$('loginBtn').disabled=true;$('loginMessage').textContent='Memeriksa akun...';try{await signInWithEmailAndPassword(auth,$('loginEmail').value.trim(),$('loginPassword').value);$('loginPassword').value=''}catch(err){$('loginMessage').textContent=err.code==='auth/invalid-credential'?'Email atau password salah.':err.message}finally{$('loginBtn').disabled=false}};$('logoutBtn').onclick=async()=>{if(confirm('Keluar dari browser ini?'))await signOut(auth)}}
boot().catch(e=>{$('loading').hidden=true;$('login').hidden=false;$('loginMessage').textContent='Gagal memulai: '+e.message;console.error(e)});
